on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

  jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: echo production