name: Test environments

on:
  push:

jobs:
  development:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo development

  testing:
    if: github.ref == 'refs/heads/testing'
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ env.ENVIRONMENT_NAME }}

  production:
    uses: './.github/actions/action.yml'
    if: github.ref == 'refs/heads/main'
    
            
